# Generated by Django 4.2.7 on 2025-06-29 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nomination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('orasta_qiz', 'ORASTA QIZ'), ('ibratli_ogil', "IBRATLI O'G'IL"), ('hafta_lideri', 'HAFTA LIDERI'), ('yosh_musavvir', 'YOSH MUSAVVIR'), ('sanat_gunchasi', "SAN'AT G'UNCHASI"), ('yosh_hunarmand', 'YOSH HUNARMAND'), ('sport_yulduzi', 'SPORT YULDUZI'), ('yosh_ijodkor', 'YOSH IJODKOR'), ('ielts', 'IELTS'), ('sat', 'SAT'), ('cefr', 'CEFR'), ('milliy_sertifikat', 'Milliy sertifikat')], max_length=50, verbose_name='Номинация')),
                ('title_ru', models.CharField(max_length=100, verbose_name='Название (RU)')),
                ('title_uz', models.CharField(max_length=100, verbose_name='Название (UZ)')),
                ('description_ru', models.TextField(verbose_name='Описание (RU)')),
                ('description_uz', models.TextField(verbose_name='Описание (UZ)')),
                ('icon', models.CharField(default='fas fa-trophy', max_length=50, verbose_name='Иконка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Номинация',
                'verbose_name_plural': 'Номинации',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(choices=[(1, '1 класс'), (2, '2 класс'), (3, '3 класс'), (4, '4 класс'), (5, '5 класс'), (6, '6 класс'), (7, '7 класс'), (8, '8 класс'), (9, '9 класс'), (10, '10 класс'), (11, '11 класс')], verbose_name='Класс')),
                ('section', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1, verbose_name='Секция')),
                ('class_teacher', models.CharField(max_length=100, verbose_name='Классный руководитель')),
                ('room_number', models.CharField(max_length=10, verbose_name='Номер кабинета')),
                ('description', models.TextField(blank=True, verbose_name='Описание класса')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Класс',
                'verbose_name_plural': 'Классы',
                'ordering': ['grade', 'section'],
                'unique_together': {('grade', 'section')},
            },
        ),
        migrations.CreateModel(
            name='SchoolSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name_ru', models.CharField(default='Школа №13', max_length=100, verbose_name='Название школы (RU)')),
                ('school_name_uz', models.CharField(default='13-maktab', max_length=100, verbose_name='Название школы (UZ)')),
                ('total_students', models.IntegerField(default=5000, verbose_name='Общее количество учеников')),
                ('total_achievements', models.IntegerField(default=12500, verbose_name='Общее количество достижений')),
                ('phone', models.CharField(default='+998 XX XXX XX XX', max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(default='info@school13.uz', max_length=254, verbose_name='Email')),
                ('address_ru', models.TextField(blank=True, verbose_name='Адрес (RU)')),
                ('address_uz', models.TextField(blank=True, verbose_name='Адрес (UZ)')),
                ('about_ru', models.TextField(blank=True, verbose_name='О школе (RU)')),
                ('about_uz', models.TextField(blank=True, verbose_name='О школе (UZ)')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=50, verbose_name='Отчество')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='students/', verbose_name='Фото')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('gender', models.CharField(choices=[('M', 'Мужской'), ('F', 'Женский')], max_length=1, verbose_name='Пол')),
                ('student_id', models.CharField(max_length=20, unique=True, verbose_name='ID ученика')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.TextField(blank=True, verbose_name='Адрес')),
                ('parent_name', models.CharField(blank=True, max_length=100, verbose_name='ФИО родителя')),
                ('parent_phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон родителя')),
                ('achievements', models.TextField(blank=True, verbose_name='Достижения')),
                ('hobbies', models.TextField(blank=True, verbose_name='Увлечения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='school_app.schoolclass', verbose_name='Класс')),
            ],
            options={
                'verbose_name': 'Ученик',
                'verbose_name_plural': 'Ученики',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='StudentNomination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement_description', models.TextField(verbose_name='Описание достижения')),
                ('date_awarded', models.DateField(verbose_name='Дата получения')),
                ('certificate_image', models.ImageField(blank=True, null=True, upload_to='certificates/', verbose_name='Сертификат')),
                ('score', models.CharField(blank=True, max_length=50, verbose_name='Балл/Результат')),
                ('nomination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='school_app.nomination', verbose_name='Номинация')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nominations', to='school_app.student', verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'Номинация ученика',
                'verbose_name_plural': 'Номинации учеников',
                'ordering': ['-date_awarded'],
                'unique_together': {('student', 'nomination')},
            },
        ),
    ]
