# Generated by Django 4.2.7 on 2025-06-29 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolclass',
            name='room_number',
        ),
        migrations.AlterField(
            model_name='schoolclass',
            name='section',
            field=models.CharField(choices=[('А', 'А'), ('Б', 'Б'), ('В', 'В'), ('Г', 'Г'), ('Д', 'Д'), ('Е', 'Е'), ('Ж', 'Ж'), ('З', 'З'), ('И', 'И'), ('К', 'К'), ('Л', 'Л')], max_length=1, verbose_name='Секция'),
        ),
    ]
