# Generated by Django 4.2.7 on 2025-06-29 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0002_remove_schoolclass_room_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True, verbose_name='ID ученика'),
        ),
    ]
