# Generated by Django 4.2.7 on 2025-06-29 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0003_alter_student_student_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название достижения')),
                ('description', models.TextField(verbose_name='Описание')),
                ('achievement_type', models.CharField(choices=[('academic', 'Академические достижения'), ('sports', 'Спортивные достижения'), ('arts', 'Творческие достижения'), ('science', 'Научные достижения'), ('social', 'Общественные достижения'), ('competition', 'Конкурсы и олимпиады'), ('international', 'Международные достижения'), ('leadership', 'Лидерство')], max_length=20, verbose_name='Тип достижения')),
                ('level', models.CharField(choices=[('school', 'Школьный уровень'), ('district', 'Районный уровень'), ('city', 'Городской уровень'), ('regional', 'Региональный уровень'), ('national', 'Национальный уровень'), ('international', 'Международный уровень')], max_length=20, verbose_name='Уровень')),
                ('date_achieved', models.DateField(verbose_name='Дата достижения')),
                ('teacher_responsible', models.CharField(blank=True, max_length=100, verbose_name='Ответственный учитель')),
                ('image', models.ImageField(blank=True, null=True, upload_to='achievements/', verbose_name='Фото')),
                ('certificate', models.ImageField(blank=True, null=True, upload_to='certificates/', verbose_name='Сертификат/Диплом')),
                ('external_link', models.URLField(blank=True, verbose_name='Внешняя ссылка')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Показать на главной')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participants', models.ManyToManyField(blank=True, to='school_app.student', verbose_name='Участники')),
            ],
            options={
                'verbose_name': 'Достижение',
                'verbose_name_plural': 'Достижения',
                'ordering': ['-date_achieved', '-created_at'],
            },
        ),
    ]
