# Generated by Django 4.2.7 on 2025-06-29 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0004_achievement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Achievement',
        ),
    ]
