# Generated by Django 5.2 on 2025-06-29 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0005_delete_achievement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nomination',
            name='icon',
        ),
        migrations.AddField(
            model_name='nomination',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='nominations/', verbose_name='Фото (изображение номинации)'),
        ),
    ]
