# Generated by Django 5.2 on 2025-06-29 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0006_remove_nomination_icon_nomination_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomination',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='nominations/', verbose_name='Изображение'),
        ),
    ]
