# Generated by Django 5.2 on 2025-06-30 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0007_alter_nomination_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolsettings',
            name='email',
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='telegram',
            field=models.CharField(default='', max_length=100, verbose_name='Telegram'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schoolclass',
            name='section',
            field=models.CharField(choices=[('А', 'А'), ('Б', 'Б'), ('В', 'В'), ('Г', 'Г'), ('Д', 'Д'), ('Е', 'Е'), ('Ж', 'Ж'), ('З', 'З'), ('И', 'И'), ('К', 'К'), ('Л', 'Л'), ('М', 'М'), ('Н', 'Н')], max_length=1, verbose_name='Секция'),
        ),
    ]
