# Generated by Django 5.2 on 2025-07-09 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0008_remove_schoolsettings_email_schoolsettings_telegram_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentnomination',
            unique_together=set(),
        ),
    ]
